export const allProjects = [
  {
    title: "NodeOps Website",
    description:
      "Built all the components for the website from scratch. Added animations using Framer Motion",
    tech: ["Next.js", "TailwindCSS", "Framer Motion"],
    demo: "https://nodeops.network/",
    github: "https:/nodeops.network/",
    isDapp: true,
    videoLink: "",
    tag: ["Curr. Organization"],
  },
  {
    title: "NodeOps Portal",
    description:
      "Built the UI for the entire product from scratch. Created Resuable UI components, integrated web3 wallets, integrated smart contracts, added animations using Framer Motion",
    tech: [
      "Next.js",
      "TailwindCSS",
      "Framer Motion",
      "@solana/web3.js",
      "wagmi",
      "zustand",
      "ethers",
    ],
    demo: "https://portal.nodeops.network/",
    github: "https://portal.nodeops.network/",
    isDapp: true,
    videoLink: "",
    tag: ["Curr. Organization"],
  },
  {
    title: "NodeOps Network",
    description:
      "Built the UI for the entire product from scratch. Created Resuable UI components, integrated web3 wallets, added animations using Framer Motion",
    tech: ["Next.js", "TailwindCSS", "Framer Motion", "Ethers.js", "Zustand"],
    demo: "https://console.nodeops.network/",
    github: "https://console.nodeops.network/",
    isDapp: true,
    videoLink: "",
    tag: ["Curr. Organization"],
  },
  {
    title: "NodeOps Cloud",
    description:
      "Built the UI for the entire product from scratch. Created Resuable UI components, integrated web3 wallets, added animations using Framer Motion",
    tech: ["Next.js", "TailwindCSS", "Framer Motion", "Ethers.js", "Zustand"],
    demo: "https://testnet.nodeops.network/",
    github: "https://testnet.nodeops.network/",
    isDapp: true,
    videoLink: "",
    tag: ["Curr. Organization"],
  },
  {
    title: "BenGrid ",
    description: "Open-source tool to create and export bento grid layouts",
    tech: ["Next.js", "TailwindCSS"],
    demo: "https://tailwind-bento.vercel.app/",
    github: "https://github.com/starc007/tailwind-bento",
    isOSS: true,
    isWeb2: true,
    videoLink: "",
    tag: ["Personal"],
  },
  {
    title: "Stylr ",
    description:
      "Make your beautiful forms in one click. Launched in Aug, 2024, got 500+ users in 1 month.",
    tech: ["Next.js", "TailwindCSS", "Nodejs", "Express", "Framer Motion"],
    demo: "https://www.stylr.xyz/",
    github: "https://www.stylr.xyz/",
    isWeb2: true,
    videoLink: "https://x.com/saurra3h/status/1823375367081738640",
    tag: ["Personal", "SaaS"],
  },
  {
    title: "walletwit",
    description:
      "Smart crypto analytics with a humorous twist. Track transactions, balances,and more in a fun and simplified way. Built this in Talent Olympics 2024 and was second runner up in Tooling Data Explorer/Dashboard",
    tech: ["Next.js", "TailwindCSS", "Solana"],
    demo: "https://walletwit.vercel.app/",
    github: "https://github.com/starc007/walletwit",
    isDapp: true,
    videoLink: "",
    tag: ["Personal", "Hackathon"],
  },
  {
    title: "Bitdroplet dapp",
    description: "Decentralised SIP platform for crypto",
    tech: ["Svelte", "TailwindCSS", "Ether.js"],
    demo: "https://bitdroplet.com/dapp/",
    isDapp: true,
    videoLink: "",
    tag: ["Prev. Organization"],
  },
  {
    title: "Zeno",
    description:
      "A decentralized Payment protocol where you can send/ buy crypto using INR. You can also Lend or swap your tokens. Built on top of Polygon",
    github: "https://github.com/starc007/zeno-prod",
    demo: "https://zenoo.netlify.app/",
    tech: ["React", "Nodejs", "Solidity"],
    isDapp: true,
    videoLink: "",
    tag: ["Personal", "Hackathon"],
  },
  {
    title: "MultiSig Wallet Smart Contract",
    description:
      "MultiSig contract + Factory contract for creating MultiSig Wallet",
    tech: ["Solidity", "hardhat"],
    github: "https://github.com/starc007/multisig-wallet",
    isDapp: true,
    videoLink: "",
    tag: ["Personal"],
  },
  {
    title: "PetRace Smart Contract",
    description:
      "Smart Contract for a Pet Racing Game. You can create your pet, upgrade them and participate in a game and win rewards.",
    tech: ["Solidity", "hardhat"],
    github: "https://github.com/starc007/petrace-smart-contract",
    isDapp: true,
    videoLink: "",
    tag: ["Personal"],
  },

  {
    title: "Sanchar",
    description:
      "A Professional Networking Platform. Used by 3000+ users. Built this product from scratch. (Frontend + Backend)",
    tech: ["Nextjs", "Typescript", "Tailwindcss", "Nodejs"],
    github: "https://github.com/starc007/piqr-frontend",
    demo: "https://sanchar.xyz",
    videoLink: "",
    isWeb2: true,
    tag: ["Personal", "Startup"],
  },
  {
    title: "Playota App (Decentralized Fantasy Game Platform.)",
    description:
      "Worked on the core feature of the app. Login, Referal, Wallet, Trumpcard game, Profile page, Socket connection",
    tech: ["React Native", "Typescript", "Reanimated", "Socket IO Client"],
    github: "https://apps.apple.com/in/app/playota/id6449972914",
    demo: "https://apps.apple.com/in/app/playota/id6449972914",
    videoLink: "",
    tag: ["Prev. Organization"],
    isDapp: true,
  },
  {
    title: "beUi",
    description:
      "Build better, build faster. A collection of free UI components & templates for your next project.",
    github: "https://github.com/starc007/ui-components",
    demo: "https://beui.saura3h.xyz",
    tech: ["React", "Typescript", "Tailwindcss", "Framer Motion"],
    isOSS: true,
    videoLink: "",
    tag: ["Personal", "Open Source"],
  },
  {
    title: "Readmi",
    description:
      "A Open Source Github readme builder. Use prebuilt templates, sections or create a new one.",
    tech: ["React", "Typescript", "Tailwindcss"],
    github: "https://github.com/starc007/readmi",
    demo: "https://readmi.xyz/",
    isOSS: true,
    videoLink: "",
    tag: ["Personal", "Open Source"],
  },
  {
    title: "Web3 Wallet Connect",
    description:
      "A Open Source wallet connection library for your decentralized application",
    github: "https://github.com/starc007/web3-wallet-connect",
    demo: "https://www.npmjs.com/package/web3-wallet-connect",
    tech: ["Typescript"],
    isOSS: true,
    videoLink: "",
    tag: ["Personal", "Open Source"],
  },

  {
    title: "Vakya AI Extension",
    description:
      "An AI extension that helps you to write coverletterin upwork and freelancer. Also you can write tweets and linkedin post using this.",
    github:
      "https://chrome.google.com/webstore/detail/vakya-your-ai-assistant/dhlkjfbdgcljpkcbmagccimbeolgiane",
    demo: "https://chrome.google.com/webstore/detail/vakya-your-ai-assistant/dhlkjfbdgcljpkcbmagccimbeolgiane",
    tech: ["Javascript", "React", "Tailwindcss", "Webpack"],
    videoLink: "",
    isWeb2: true,
    tag: ["Personal", "Freelance"],
  },
  {
    title: "Playota",
    description: "A decentralized fantasy game platform.",
    github: "https://playota.app",
    demo: "https://playota.app",
    tech: ["Nextjs", "Typescript", "Tailwindcss", "Framer Motion"],
    videoLink: "",
    tag: ["Prev. Organization"],
    isDapp: true,
  },

  {
    title: "Simple",
    description:
      "A decentralized doc sharing and collaborating web app. Built on top of IPFS and Polygon",
    github: "https://github.com/starc007/simple",
    demo: "https://simpldapp.netlify.app/",
    tech: ["React", "Nodejs", "NFT Port"],
    isDapp: true,
    videoLink: "",
    tag: ["Personal", "Hackathon"],
  },
  {
    title: "Senju",
    description:
      "A decentralized blogging platform. Built on top of IPFS and Polygon. you can import your blogs from other platforms or write your own and mint them as NFT",
    github: "https://senju-test.netlify.app",
    demo: "https://senju-test.netlify.app",
    tech: ["React", "Nodejs", "Redux", "Onec Tools"],
    isDapp: true,
    videoLink: "",
    tag: ["Personal", "Startup"],
  },
  {
    title: "Powerloom",
    description:
      "Worked with Powerloom for 3 months as a part-time Frontend dev (March 2024 - May 2024)",
    tech: ["Svelte", "TailwindCSS", "Typescript", "Nodejs"],
    isFreelance: true,
    videoLink: "",
    tag: ["Personal", "Freelance"],
  },
  {
    title: "Polygon Freelance Work",
    description:
      "Worked with Polygon for 2 small projects as a Freelance dev - Frontend",
    tech: ["React"],
    isFreelance: true,
    videoLink: "",
    tag: ["Personal", "Freelance"],
  },
  {
    title: "Social Defi",
    description: "Wrote Smart Contract for a Social Defi Platform",
    tech: ["Solidity", "hardhat"],
    demo: "https://basescan.org/address/0x3158535153Ad4259f2e21763D0Eb566Ee9DaEA78#code",
    isFreelance: true,
    videoLink: "",
    tag: ["Personal", "Freelance"],
  },
];
